### ISSUE TITLE
Feature: User can create a room

### ISSUE THREAD

**Issue by amyaitran** [amyaitran/oft-topic-game#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- user can create a room that others can join using a room code

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- a new game can be created on the desktop page
- pressing the "Create a new game!" button will generate a game code that will appear on the screen

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/30616230/139764381-094df5d0-caf2-4bec-94ec-d7ac01f91070.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to the SQL file generated from dbdesigner
- [x] Revise SQL file to remove "public" prefix
- [x] Run db import to create database

### ☁️ Server

- [x] Insert room code to gameId in table "game"
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a button component that will create a new game
- [x] Write a randomizer function that will generate a 4-letter room code
- [x] View swap button to display room code 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
