### ISSUE TITLE
Feature: User can join a room

### ISSUE THREAD

**Issue by amyaitran** [amyaitran/oft-topic-game#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- user can join a room using a created room code

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- on a mobile screen, user can visit a URL path that will have input fields for "name" and "game code"
- when a valid name and game code are entered, user will be able to join a room

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/30616230/140167007-91153806-4e9c-4784-b4a3-d864ec898675.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to update "players" table with the user's inputted name

### ☁️ Server

- [x] Update `server/index.js` to take in path for mobile screen to input name and room code
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a form component to that will take in a user's "name" and "game code"

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
