### ISSUE TITLE
Feature: User can disqualify duplicate answers

### ISSUE THREAD

**Issue by amyaitran** [amyaitran/oft-topic-game#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can disqualify duplicate answers
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- after timer runs out, all answers are submitted
- on desktop, screen will change to display instructions for disqualifier phase
- on mobile, users will see all answers from all players for a selected prompt
- on marking the checkbox, duplicate answers will be moved to "duplicate answers" box and only unique answers will remain in "original answers"
- when finished, user can submit

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/30616230/141183697-2c79a52a-42c0-44c8-aeb7-1445fa909c15.png)

![image](https://user-images.githubusercontent.com/30616230/141184239-32753ee3-cfd6-48a0-a9e0-f767452e27ad.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `data.sql` to take player answers

### ☁️ Server

- [ ] Update `server/index.js` to 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to display answers and separate them by original/duplicate

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
